# Schema for the configuration files of the votingapi module.

votingapi.settings:
  type: mapping
  label: 'VotingApi settings'
  mapping:
    anonymous_window:
      type: integer
      label: 'Anonymous vote rollover'
    user_window:
      type: integer
      label: 'Registered user vote rollover'
    calculation_schedule:
      type: string
      label: 'Vote tallying'
